# Cross-compiler for Ubuntu.
services:
  builder:
    build:
      context: ..
    # The dockerfile builds the project; we just need to copy the artifact to the volume.
    command: cp site2 /output/mysite2.fcgi
    volumes:
      - ./build:/output
