# Cross-compiler for Ubuntu.
services:
  builder:
    build:
      context: ..
    # The dockerfile builds the project; we just need to copy the artifacts to the volume.
    command: bash -c "cp site2 /output/mysite2.fcgi && rsync -a gens/ /output/gens/"
    volumes:
      - ./build:/output
